language: go
go:
  - 1.13.1
script:
  - ./util.sh build
deploy:
  provider: releases
  api_key:
    secure: Im7rK4WHEBhP7lSUNGegK7lLmibsA+p/6aeBWqLEGEjPkqdZXm2yIHN8k/OIUJrZ2RDOmirXAwBs0AdWG8svRBM7zKw7yc3nl5kwQYUIvuiIXXinCFTp3RalwKhDPYZqSY8EsefoF1tUWBHGmCdILqfhNxlMXsP4B5N3A1iv54FfjXT4QOyn2AJMQd9Q3so0buA67JB+OOlac+K728egdzMIjtcCZi27GT6QJTVyWemLU55fXtObgyRF5+eL+6YW4r6s3lh4zpYZcznFHTIiF2qn//yKE0y7RDcIwLJOGVMrSjoeJUnDaeCwLtdQHD8Az5hwvH8TL4Mp6KszHK7A/scSyrNr+7AnGhlnHH7fqJfaFF/22tngcm6YcDYSSQxPVv9vl/V46S6lf7fK+Uz9TGWJW+F3STI4E5OyQl2Pt/V4+amT27LxduIZ8cyBxNRo9RbCTRTsuZ8hn5QPIXFidvHfWhk4hP/VDegZ6amnN0i8V5YW+GARzQXx8N97hCKPRNR+m5DVi5UvUjM1TUpCgxnICNANip/muuiL2SExM2rFDWpVhd9Q7fY08jzVmbhpt5wyAtW8njOY605wEipPf9GarPcocwIO+xyUs14VyU99EeOuxUqx6EfqlHlv5vX8vto/5hDFI3StbiIxoYx7wwiL7ElXbSzNP9AOPqxQ0MA=
  file: pi-alarm
  skip_cleanup: true
  on:
    repo: andrewmarklloyd/pi-alarm
    tags: true
